name: Pull Request

on:
  pull_request

jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Build
        run: |
          python -m pip install --upgrade pip
          python -m pip install setuptools wheel twine
          python -m pip install -r requirements.txt
          python setup.py test
